[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.12
    adafruit/RTClib @ ^2.1.4
